// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHi07PheibgbQdCnnblARCWvVQVo_SrYM',
    appId: '1:40128014479:web:43fb18cbd201a0884528fa',
    messagingSenderId: '40128014479',
    projectId: 'mini-expense-tracker-2a8e1',
    authDomain: 'mini-expense-tracker-2a8e1.firebaseapp.com',
    storageBucket: 'mini-expense-tracker-2a8e1.firebasestorage.app',
    measurementId: 'G-B7LT6P2ZCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAreBx56YB47WWB3SSlmpS8pC_SRXQB2U',
    appId: '1:40128014479:android:9e867755672b99d34528fa',
    messagingSenderId: '40128014479',
    projectId: 'mini-expense-tracker-2a8e1',
    storageBucket: 'mini-expense-tracker-2a8e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRXuM5HtpGClGP8xWSEvY1oxpBqQWzKhs',
    appId: '1:40128014479:ios:c1149f94e8ca5ad84528fa',
    messagingSenderId: '40128014479',
    projectId: 'mini-expense-tracker-2a8e1',
    storageBucket: 'mini-expense-tracker-2a8e1.firebasestorage.app',
    iosClientId: '40128014479-di9669i5ilpq2i33k0tk6u71l8g25u6m.apps.googleusercontent.com',
    iosBundleId: 'com.miniexpense.miniExpenseTracker',
  );
}
